/**
 *
 * @author elena
 */

package GUI;

import java.util.ArrayList;
import java.awt.Component;

import deepspace.SpaceStationToUI;
import deepspace.ShieldToUI;
import deepspace.WeaponToUI;
import deepspace.GameState;

public class SpaceStationView extends javax.swing.JPanel {
    private HangarView hv;
    
    public SpaceStationView() {
        initComponents();
    }
    
    void setSpaceStation(SpaceStationToUI s){
        weapons_panel.removeAll();
        shields_panel.removeAll();
        hangar_panel.removeAll();
        
        ammoPower.setText(Float.toString(s.getAmmoPower()));
        fuelUnits.setText(Float.toString(s.getFuelUnits()));
        nMedals.setText(Integer.toString(s.getnMedals()));
        shieldPower.setText(Float.toString(s.getShieldPower()));
        
        HangarView h= new HangarView();
        if(s.getHangar() != null){
            h.setHangar(s.getHangar());
            hangar_panel.add(h);
        }
        
        WeaponView wv;
        for(WeaponToUI w: s.getWeapons()){
            wv= new WeaponView();
            wv.setWeapon(w);
            weapons_panel.add(wv);
        }
        
        ShieldBoosterView sv;
        for(ShieldToUI sh: s.getShieldBoosters()){
            sv= new ShieldBoosterView();
            sv.setShieldBooster(sh);
            shields_panel.add(sv);
        }
        
        if( MainView.controller.getState() == GameState.INIT || MainView.controller.getState() == GameState.AFTERCOMBAT ){
            equip.setEnabled(true);
            discard.setEnabled(true);
            discard_hangar.setEnabled(true);
        }
        else{
            equip.setEnabled(false);
            discard.setEnabled(false);
            discard_hangar.setEnabled(false);
        }
        
        repaint();
        revalidate();
    }
    
    ArrayList<Integer> getSelectedWeapons(){
        ArrayList<Integer> selected_weapons= new ArrayList();
        int i= 0;
        for (Component c : getComponents()){
            try{
                if(((WeaponView) c).isSelected())
                    selected_weapons.add(i);
            }
            catch(Exception e){}
            i++;
        }
        return selected_weapons;
    }
    
    ArrayList<Integer> getSelectedShields(){
        ArrayList<Integer> selected_shields= new ArrayList();
        int i= 0;
        for(Component c: getComponents()){
            try{
                if(((ShieldBoosterView) c).isSelected())
                    selected_shields.add(i); 
            }
            catch(Exception e){}
            i++;
        }  
        return selected_shields;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        shieldPower = new javax.swing.JTextField();
        ammoPower = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        fuelUnits = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        nMedals = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        weapons_panel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        shields_panel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        hangar_panel = new javax.swing.JPanel();
        equip = new javax.swing.JButton();
        discard = new javax.swing.JButton();
        discard_hangar = new javax.swing.JButton();

        jLabel1.setText("Potencia de ataque: ");

        jLabel2.setText("Potencia de defensa: ");

        shieldPower.setText("jTextField1");

        ammoPower.setText("jTextField2");

        jLabel3.setText("Nivel de combustible: ");

        fuelUnits.setText("jTextField3");

        jLabel4.setText("Medallas: ");

        nMedals.setText("jTextField4");

        weapons_panel.setBorder(javax.swing.BorderFactory.createTitledBorder("Armas"));
        jScrollPane1.setViewportView(weapons_panel);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        shields_panel.setBorder(javax.swing.BorderFactory.createTitledBorder("Escudos"));
        jScrollPane2.setViewportView(shields_panel);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        hangar_panel.setBorder(javax.swing.BorderFactory.createTitledBorder("Hangar"));
        jScrollPane3.setViewportView(hangar_panel);

        equip.setText("Equipar");
        equip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equipActionPerformed(evt);
            }
        });

        discard.setText("Descartar");
        discard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discardActionPerformed(evt);
            }
        });

        discard_hangar.setText("Descartar hangar completo");
        discard_hangar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discard_hangarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(shieldPower, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ammoPower, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(fuelUnits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(nMedals, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(equip)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(discard)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(discard_hangar)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ammoPower, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(fuelUnits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(shieldPower, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(nMedals, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(equip)
                    .addComponent(discard)
                    .addComponent(discard_hangar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void equipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equipActionPerformed
        MainView.controller.mountItems(hv.getSelectedWeapons(), hv.getSelectedShields());
    }//GEN-LAST:event_equipActionPerformed

    private void discardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discardActionPerformed
        MainView.controller.discardItemsInHangar(hv.getSelectedWeapons(), hv.getSelectedShields());
        MainView.controller.discardShields(getSelectedShields());
        MainView.controller.discardWeapons(getSelectedWeapons());
        MainView.controller.updateView();
    }//GEN-LAST:event_discardActionPerformed

    private void discard_hangarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discard_hangarActionPerformed
        MainView.controller.discardHangar();
    }//GEN-LAST:event_discard_hangarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ammoPower;
    private javax.swing.JButton discard;
    private javax.swing.JButton discard_hangar;
    private javax.swing.JButton equip;
    private javax.swing.JTextField fuelUnits;
    private javax.swing.JPanel hangar_panel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField nMedals;
    private javax.swing.JTextField shieldPower;
    private javax.swing.JPanel shields_panel;
    private javax.swing.JPanel weapons_panel;
    // End of variables declaration//GEN-END:variables
}
